name: Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install Dependencies
      working-directory: ./flujoai-frontend
      run: npm install --legacy-peer-deps

    - name: Build
      working-directory: ./flujoai-frontend
      run: npm run build